# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8f74688932f4c471ae614bbb163e452fef956eec92ed0fd8d0a7451bc17caa887a72b585c57f0e9b8917829f26f21cdc76fe553b59215146c92c5d46860d5f3c
  api_client_token: 'api-dev'

test:
  secret_key_base: 462f77c4186f4513465203f38fe33b1b3543b366f220e3d31c0be1ac7b6dfe7245af99a71460036dae8d7ac09aeced085630cc2d859c1b8cafc8c30400308858
  api_client_token: 'api-test'

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  api_client_token: <%= ENV["API_CLIENT_TOKEN"] %>
